# Generated by Django 4.2.16 on 2024-12-04 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0002_usermodel_groups_usermodel_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientRepository",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("datlich.patient",),
        ),
        migrations.CreateModel(
            name="UserRepository",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("datlich.usermodel",),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="description",
            field=models.TextField(blank=None, null=True),
        ),
        migrations.AddField(
            model_name="medicalrecord",
            name="medical_results",
            field=models.TextField(blank=None, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_ready",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="benhnen",
            field=models.TextField(blank=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="cannang",
            field=models.FloatField(blank=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="chieucao",
            field=models.FloatField(blank=None),
        ),
        migrations.AlterField(
            model_name="patient",
            name="nhommau",
            field=models.CharField(blank=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="shift",
            field=models.ForeignKey(
                blank=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="datlich.shift",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Đang chờ"), (1, "Đã hoàn thành"), (2, "Đã bỏ lỡ")]
            ),
        ),
    ]
