# Generated by Django 4.2.16 on 2024-12-04 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0004_doctor_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="patient",
            field=models.ForeignKey(
                blank=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="datlich.patient",
            ),
        ),
    ]
