# Generated by Django 4.2.16 on 2024-12-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0005_alter_schedule_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/images/"
            ),
        ),
    ]
