# Generated by Django 4.2.16 on 2024-12-06 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0006_article_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rate",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PatientRepository",
        ),
        migrations.AddField(
            model_name="doctor",
            name="average_rate",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="rate",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="datlich.doctor",
            ),
        ),
        migrations.AddField(
            model_name="rate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_rates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
