# Generated by Django 4.2.16 on 2024-12-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0007_rate_delete_patientrepository_doctor_average_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
