# Generated by Django 4.2.16 on 2024-12-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0008_usermodel_is_staff_alter_usermodel_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="rate",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
