# Generated by Django 4.2.16 on 2024-12-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0011_like_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="is_like",
            field=models.BooleanField(default=True),
        ),
    ]
