# Generated by Django 4.2.16 on 2024-12-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0012_alter_like_is_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="is_like",
        ),
        migrations.AddField(
            model_name="article",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
