# Generated by Django 4.2.16 on 2024-12-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0013_remove_like_is_like_article_like_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
