# Generated by Django 4.2.16 on 2024-12-13 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datlich", "0014_schedule_notified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="avatar",
        ),
    ]
